{{- if .Values.zabbixServer.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "zabbix.fullname" . }}-zabbix-server
  labels:
    app: {{ template "zabbix.fullname" . }}-zabbix-server
    app.kubernetes.io/name: zabbix-server
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-server
    app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-server
    {{- if .Values.zabbixServer.deploymentLabels }}
    {{- toYaml .Values.zabbixServer.deploymentLabels | nindent 4 }}
    {{- end }}
  annotations:
    {{- range $key,$value := .Values.zabbixServer.deploymentAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.zabbixServer.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "zabbix.fullname" . }}-zabbix-server
  template:
    metadata:
      annotations:
        {{- range $key,$value := .Values.zabbixServer.containerAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      labels:
        app: {{ template "zabbix.fullname" . }}-zabbix-server
        app.kubernetes.io/name: zabbix-server
        helm.sh/chart: {{ include "zabbix.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-server
        app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-server
        {{- if .Values.zabbixServer.containerLabels }}
        {{- toYaml .Values.zabbixServer.containerLabels | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "zabbix.serviceAccountName" . }}
      {{- with .Values.zabbixServer.extraPodSpecs }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if gt (len .Values.affinity) 0 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- else if .Values.zabbixServer.podAntiAffinity }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-server
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      {{- if gt (.Values.zabbixServer.replicaCount | int) 1 }}
        - name: init-wait-for-database-schema
          {{- if .Values.zabbixServer.image.tag }}
          image: "{{ .Values.zabbixServer.image.repository }}:{{ .Values.zabbixServer.image.tag }}"
          {{- else }}
          image: "{{ .Values.zabbixServer.image.repository }}:{{ .Values.zabbixImageTag }}"
          {{- end }}
          env:
          securityContext:
            {{- toYaml .Values.zabbixServer.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.zabbixServer.resources | nindent 12 }}
          command:
            - "/bin/bash"
            - "/script/wait_db_schema.sh"
          volumeMounts:
            - name: init-waitschema-script
              mountPath: /script
      {{- end }}
      {{- with .Values.zabbixServer.extraInitContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: zabbix-server
          resources:
            {{- toYaml .Values.zabbixServer.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.zabbixServer.securityContext | nindent 12 }}
          {{- if .Values.zabbixServer.image.tag }}
          image: "{{ .Values.zabbixServer.image.repository }}:{{ .Values.zabbixServer.image.tag }}"
          {{- else }}
          image: "{{ .Values.zabbixServer.image.repository }}:{{ .Values.zabbixImageTag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.zabbixServer.image.pullPolicy }}
          ports:
            - containerPort: 10051
              name: zabbix-server
              {{- if (default false .Values.zabbixServer.hostPort) }}
              hostPort: 10051
              {{- end }}
              {{- if ne "0.0.0.0" .Values.zabbixServer.hostIP }}
              hostIP: {{ .Values.zabbixServer.hostIP }}
              {{- end}}
            - containerPort: 10052
              name: zabbix-jmx
              {{- if (default false .Values.zabbixServer.hostPort) }}
              hostPort: 10052
              {{- end }}
              {{- if ne "0.0.0.0" .Values.zabbixServer.hostIP }}
              hostIP: {{ .Values.zabbixServer.hostIP }}
              {{- end}}
          env:
            {{- include "zabbix.mysqlAccess.variables" (list $ . "zabbix") | nindent 12 }}
            {{- range $item := .Values.zabbixServer.extraEnv }}
            - name: {{ $item.name }}
              value: {{ $item.value | quote }}
            {{- end }}
            - name: ZBX_AUTOHANODENAME
              value: "hostname"
            - name: ZBX_NODEADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          {{- with .Values.zabbixServer.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.zabbixServer.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.zabbixServer.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.zabbixServer.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      imagePullSecrets:
      {{- range .Values.zabbixServer.image.pullSecrets }}
        - name: {{ . | quote }}
      {{- end }}
      {{- range .Values.zabbixAgent.image.pullSecrets }}
        - name: {{ . | quote }}
      {{- end }}
      volumes:
      {{- if gt (.Values.zabbixServer.replicaCount | int) 1 }}
        - name: init-waitschema-script
          configMap:
            name: {{ template "zabbix.fullname" . }}-waitdbschema-script
      {{- end }}
      {{- with .Values.zabbixServer.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
