{{- if .Values.zabbixServer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zabbix.fullname" . }}-zabbix-server
  labels:
    app: {{ template "zabbix.fullname" . }}-zabbix-server
    app.kubernetes.io/name: zabbix-server
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-server
    app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-server
  {{- if .Values.zabbixServer.service.annotations }}
  annotations:
    {{- range $key,$value := .Values.zabbixServer.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.zabbixServer.service.type }}
  {{- if .Values.zabbixServer.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.zabbixServer.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.zabbixServer.service.externalIPs }}
  externalIPs: {{ .Values.zabbixServer.service.externalIPs | toYaml | nindent 6 }}
  {{- end }}
  {{- if .Values.zabbixServer.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.zabbixServer.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.zabbixServer.service.clusterIP }}
  clusterIP: {{ .Values.zabbixServer.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.zabbixServer.service.port }}
      targetPort: 10051
      name: zabbix-server
      protocol: TCP
      {{- if ( and (eq .Values.zabbixServer.service.type "NodePort" ) (not (empty .Values.zabbixServer.service.nodePort)) ) }}
      nodePort: {{ .Values.zabbixServer.service.nodePort }}
      {{- end }}
    - port: 10052
      targetPort: 10052
      protocol: TCP
      name: zabbix-jmx
  selector:
    app: {{ template "zabbix.fullname" . }}-zabbix-server
{{- end }}


{{- if .Values.zabbixWeb.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zabbix.fullname" . }}-zabbix-web
  labels:
    app: {{ template "zabbix.fullname" . }}-zabbix-web
    app.kubernetes.io/name: zabbix-web
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-web
    app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-web
  {{- if .Values.zabbixWeb.service.annotations }}
  annotations:
    {{- range $key,$value := .Values.zabbixWeb.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.zabbixWeb.service.type }}
  {{- if .Values.zabbixWeb.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.zabbixWeb.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.zabbixWeb.service.externalIPs }}
  externalIPs: {{ .Values.zabbixWeb.service.externalIPs | toYaml | nindent 6 }}
  {{- end }}
  {{- if .Values.zabbixWeb.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.zabbixWeb.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.zabbixWeb.service.clusterIP }}
  clusterIP: {{ .Values.zabbixWeb.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.zabbixWeb.service.port }}
      targetPort: 8080
      protocol: TCP
      name: zabbix-web
      {{- if ( and (eq .Values.zabbixWeb.service.type "NodePort" ) (not (empty .Values.zabbixWeb.service.nodePort)) ) }}
      nodePort: {{ .Values.zabbixWeb.service.nodePort }}
      {{- end }}
  selector:
    app: {{ template "zabbix.fullname" . }}-zabbix-web
  {{- end }}